dev:
	PORT=3000 DATABASE_URL="root:root@(localhost)/ginder_access_tokens?charset=utf8&parseTime=True&loc=Local" JWT_SECRET=ginder_oauth_ms USERS_URL=https://ginder-users-api.herokuapp.com go run main.go
